import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <h1>Here is Header Area</h1>
      </Head>

      <main>
        <h1>Welcome to Justin Toy project</h1>
        <div>Here is Main body</div>
      </main>

      <footer>
        <h1>Here is footer Area</h1>
      </footer>
    </div>
  );
};

export default Home;
